{% set name = "sphinxcontrib-towncrier" %}
{% set version = "0.5.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 294e69df6e275e7a86df7ea6a927cc7c28c2c370a884cd5c45de6ec989858f27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - setuptools-scm >=3.5
    - setuptools_scm_git_archive >=1.1
    - pip
  run:
    - python >={{ python_min }}
    - sphinx
    - towncrier >=19.2

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sphinx-contrib/sphinxcontrib-towncrier
  summary: An RST directive for injecting a Towncrier-generated changelog draft containing fragments for the unreleased (next) project version
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
